// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginReqPro.proto

package cn.huizhi.message.player;

public final class LoginByPidReqPro {
  private LoginByPidReqPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginByPidReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 pid = 1;
    /**
     * <code>optional int32 pid = 1;</code>
     */
    boolean hasPid();
    /**
     * <code>optional int32 pid = 1;</code>
     */
    int getPid();
  }
  /**
   * Protobuf type {@code NetProtocol.LoginByPidReq}
   */
  public static final class LoginByPidReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginByPidReqOrBuilder {
    // Use LoginByPidReq.newBuilder() to construct.
    private LoginByPidReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginByPidReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginByPidReq defaultInstance;
    public static LoginByPidReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginByPidReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginByPidReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.huizhi.message.player.LoginByPidReqPro.internal_static_NetProtocol_LoginByPidReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.huizhi.message.player.LoginByPidReqPro.internal_static_NetProtocol_LoginByPidReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq.class, cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginByPidReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginByPidReq>() {
      public LoginByPidReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginByPidReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginByPidReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 pid = 1;
    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    /**
     * <code>optional int32 pid = 1;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 pid = 1;</code>
     */
    public int getPid() {
      return pid_;
    }

    private void initFields() {
      pid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, pid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetProtocol.LoginByPidReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.huizhi.message.player.LoginByPidReqPro.internal_static_NetProtocol_LoginByPidReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.huizhi.message.player.LoginByPidReqPro.internal_static_NetProtocol_LoginByPidReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq.class, cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq.Builder.class);
      }

      // Construct using cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.huizhi.message.player.LoginByPidReqPro.internal_static_NetProtocol_LoginByPidReq_descriptor;
      }

      public cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq getDefaultInstanceForType() {
        return cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq.getDefaultInstance();
      }

      public cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq build() {
        cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq buildPartial() {
        cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq result = new cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pid_ = pid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq) {
          return mergeFrom((cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq other) {
        if (other == cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq.getDefaultInstance()) return this;
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.huizhi.message.player.LoginByPidReqPro.LoginByPidReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 pid = 1;
      private int pid_ ;
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000001;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pid = 1;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetProtocol.LoginByPidReq)
    }

    static {
      defaultInstance = new LoginByPidReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetProtocol.LoginByPidReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetProtocol_LoginByPidReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetProtocol_LoginByPidReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021LoginReqPro.proto\022\013NetProtocol\"\034\n\rLogi" +
      "nByPidReq\022\013\n\003pid\030\001 \001(\005B.\n\030cn.huizhi.mess" +
      "age.playerB\020LoginByPidReqProH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NetProtocol_LoginByPidReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NetProtocol_LoginByPidReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetProtocol_LoginByPidReq_descriptor,
              new java.lang.String[] { "Pid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
